{"@t":"2019-04-21T02:58:24.9022221Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.0.1 on A698542C2CB0.","TimingId":"7e24ebb","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":1656,"ProcessName":"w3wp","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"52460bbc-8555-4e9d-bc5c-192bb2d606f8"}
{"@t":"2019-04-21T02:58:25.1284417Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.MainDom","ProcessId":1656,"ProcessName":"w3wp","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"52460bbc-8555-4e9d-bc5c-192bb2d606f8"}
{"@t":"2019-04-21T02:58:25.1284417Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.MainDom","ProcessId":1656,"ProcessName":"w3wp","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"52460bbc-8555-4e9d-bc5c-192bb2d606f8"}
{"@t":"2019-04-21T02:58:25.1440437Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"2cd3350","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":1656,"ProcessName":"w3wp","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"52460bbc-8555-4e9d-bc5c-192bb2d606f8"}
{"@t":"2019-04-21T02:58:25.3784384Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":236,"TimingId":"2cd3350","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":1656,"ProcessName":"w3wp","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"52460bbc-8555-4e9d-bc5c-192bb2d606f8"}
{"@t":"2019-04-21T02:58:27.6596634Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":1656,"ProcessName":"w3wp","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"52460bbc-8555-4e9d-bc5c-192bb2d606f8"}
{"@t":"2019-04-21T02:58:28.7378084Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":3840,"TimingId":"7e24ebb","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":1656,"ProcessName":"w3wp","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"52460bbc-8555-4e9d-bc5c-192bb2d606f8"}
{"@t":"2019-04-21T02:58:29.4252815Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://172.22.97.87:80/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":1656,"ProcessName":"w3wp","ThreadId":5,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"7a0e0187-0f3c-462e-95d7-568aa075ee46"}
{"@t":"2019-04-21T02:58:29.4409032Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://172.22.97.87:80/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":1656,"ProcessName":"w3wp","ThreadId":5,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"7a0e0187-0f3c-462e-95d7-568aa075ee46"}
{"@t":"2019-04-21T02:58:30.2008958Z","@mt":"Umbraco must install or upgrade.","@l":"Warning","SourceContext":"Umbraco.Web.UmbracoModule","ProcessId":1656,"ProcessName":"w3wp","ThreadId":5,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"WARN ","HttpRequestNumber":2,"HttpRequestId":"7a0e0187-0f3c-462e-95d7-568aa075ee46"}
{"@t":"2019-04-21T03:03:28.1960367Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network location cannot be reached. For information about network troubleshooting, see Windows Help\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:1231,State:0,Class:20","SourceContext":"System.Data.IDbConnection","ProcessId":1656,"ProcessName":"w3wp","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"WARN ","HttpRequestNumber":3,"HttpRequestId":"4ef0662c-c489-4034-ab28-44fb2ad8ba49"}
{"@t":"2019-04-21T03:04:46.2230260Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:e98811de-79f7-47be-bacb-7760caf2f5b7\r\nError Number:18456,State:1,Class:14","SourceContext":"System.Data.IDbConnection","ProcessId":1656,"ProcessName":"w3wp","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"WARN ","HttpRequestNumber":4,"HttpRequestId":"d77ecd35-129a-4bac-a419-1202b4e29ea9"}
{"@t":"2019-04-21T03:05:51.8753264Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:a6844fe3-dc28-42dc-9d30-d44ea324fb9f\r\nError Number:18456,State:1,Class:14","SourceContext":"System.Data.IDbConnection","ProcessId":1656,"ProcessName":"w3wp","ThreadId":15,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"WARN ","HttpRequestNumber":5,"HttpRequestId":"53e863f8-9aed-4a1a-bbbf-fc2aafa96d70"}
{"@t":"2019-04-21T03:05:56.4121866Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'sa'.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)\r\nClientConnectionId:a6844fe3-dc28-42dc-9d30-d44ea324fb9f\r\nError Number:18456,State:1,Class:14","SourceContext":"System.Data.IDbConnection","ProcessId":1656,"ProcessName":"w3wp","ThreadId":12,"AppDomainId":2,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"A698542C2CB0","Log4NetLevel":"WARN ","HttpRequestNumber":6,"HttpRequestId":"d21846ed-6dd4-4681-a5a5-fe41c74490fc"}
